---
- name: Configure modules for kubernetes and containerd
  blockinfile:
    path: /etc/modules-load.d/kubernetes_containerd.conf
    create: yes
    block: |
      overlay
      br_netfilter
##
- name: Load modules at runtime
  shell: modprobe overlay; modprobe br_netfilter
  args:
    warn: false
##
- name: Configure sysctl params kubernetes networking
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
##
- name: Reload sysctl configs
  shell: sysctl --system
  args:
    warn: false
##
- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*)swap(.*)$'
    replace: '#\1'
##
- name: Disable SWAP at runtime
  shell: swapoff -a
  args:
    warn: false
##
- name: Configure hosts files with don't have DNS server
  template:
    src: hosts.j2
    dest: /etc/hosts
...
